"""empty message

Revision ID: 9db8643e40d0
Revises: 5d01639a087e
Create Date: 2022-11-14 10:08:10.572279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db8643e40d0'
down_revision = '5d01639a087e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
